stages:
  - prepare
  - database

image: drakona/php:7.4-symfony

build:
  stage: prepare
  script:
    - composer install
  cache:
    paths:
      - vendor
    policy: push

npm:
  stage: prepare
  script: npm install
  cache:
    paths:
      - node_modules
    policy: push

database:
  stage: database
  script: echo 'database'
  dependencies:
    - build
    - npm
  cache:
    paths:
      - vendor
      - node_modules
    policy: pull